REM Build Bat File
REM Copmile c file 
"C:\ARM\ADSv1_2\Bin\armcc" -O2 -g -apcs /ropi/rwpi -cpu ARM7EJ-S -o "D:\UNISDK\ScrollShooter\VXP\arm\vmmain.o" -c "C:\MRE_SDK\lib\MRE10\src\vmmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_176X220__ -I "C:\MRE_SDK\include" -I "C:\MRE_SDK\include\service" -I "C:\MRE_SDK\include" -I "C:\MRE_SDK\include\service" -I "D:\UNISDK\ScrollShooter\VXP\include" -I "D:\UNISDK\ScrollShooter\VXP\include\service" -I "D:\UNISDK\ScrollShooter\VXP\include\component" -I "D:\UNISDK\ScrollShooter\VXP\ResID" -I "D:\UNISDK\ScrollShooter\VXP\src\app\widget" -I "D:\UNISDK\ScrollShooter\VXP\src\app\launcher" -I "D:\UNISDK\ScrollShooter\VXP\src\app\wallpaper" -I "D:\UNISDK\ScrollShooter\VXP\src\app\screen_lock" -I "D:\UNISDK\ScrollShooter\VXP\include\service" -I "D:\UNISDK\ScrollShooter\VXP\include\component" -I "D:\UNISDK\ScrollShooter\VXP\include\service" -I "D:\UNISDK\ScrollShooter\VXP\src\framework" -I "D:\UNISDK\ScrollShooter\VXP\src\framework\ui_core\base" -I "D:\UNISDK\ScrollShooter\VXP\src\framework\ui_core\mvc" -I "D:\UNISDK\ScrollShooter\VXP\src\framework\ui_core\pme" -I "D:\UNISDK\ScrollShooter\VXP\src\framework\mmi_core" -I "D:\UNISDK\ScrollShooter\VXP\src\ui_engine\vrt\interface" -I "D:\UNISDK\ScrollShooter\VXP\src\component" -I "D:\UNISDK\ScrollShooter\VXP\src\ui_engine\framework\xml" -I "D:\UNISDK\ScrollShooter\VXP" -errors "D:\UNISDK\ScrollShooter\VXP\VXP.log"
REM Copmile c file 
"C:\ARM\ADSv1_2\Bin\armcc" -O2 -g -apcs /ropi/rwpi -cpu ARM7EJ-S -o "D:\UNISDK\ScrollShooter\VXP\arm\plat_vxp.o" -c "d:\UNISDK\ScrollShooter\src\platform\plat_vxp.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_176X220__ -I "C:\MRE_SDK\include" -I "C:\MRE_SDK\include\service" -I "C:\MRE_SDK\include" -I "C:\MRE_SDK\include\service" -I "D:\UNISDK\ScrollShooter\VXP\include" -I "D:\UNISDK\ScrollShooter\VXP\include\service" -I "D:\UNISDK\ScrollShooter\VXP\include\component" -I "D:\UNISDK\ScrollShooter\VXP\ResID" -I "D:\UNISDK\ScrollShooter\VXP\src\app\widget" -I "D:\UNISDK\ScrollShooter\VXP\src\app\launcher" -I "D:\UNISDK\ScrollShooter\VXP\src\app\wallpaper" -I "D:\UNISDK\ScrollShooter\VXP\src\app\screen_lock" -I "D:\UNISDK\ScrollShooter\VXP\include\service" -I "D:\UNISDK\ScrollShooter\VXP\include\component" -I "D:\UNISDK\ScrollShooter\VXP\include\service" -I "D:\UNISDK\ScrollShooter\VXP\src\framework" -I "D:\UNISDK\ScrollShooter\VXP\src\framework\ui_core\base" -I "D:\UNISDK\ScrollShooter\VXP\src\framework\ui_core\mvc" -I "D:\UNISDK\ScrollShooter\VXP\src\framework\ui_core\pme" -I "D:\UNISDK\ScrollShooter\VXP\src\framework\mmi_core" -I "D:\UNISDK\ScrollShooter\VXP\src\ui_engine\vrt\interface" -I "D:\UNISDK\ScrollShooter\VXP\src\component" -I "D:\UNISDK\ScrollShooter\VXP\src\ui_engine\framework\xml" -I "D:\UNISDK\ScrollShooter\VXP" -errors "D:\UNISDK\ScrollShooter\VXP\VXP.log"
REM Copmile c file 
"C:\ARM\ADSv1_2\Bin\armcc" -O2 -g -apcs /ropi/rwpi -cpu ARM7EJ-S -o "D:\UNISDK\ScrollShooter\VXP\arm\game.o" -c "d:\UNISDK\ScrollShooter\src\game.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_176X220__ -I "C:\MRE_SDK\include" -I "C:\MRE_SDK\include\service" -I "C:\MRE_SDK\include" -I "C:\MRE_SDK\include\service" -I "D:\UNISDK\ScrollShooter\VXP\include" -I "D:\UNISDK\ScrollShooter\VXP\include\service" -I "D:\UNISDK\ScrollShooter\VXP\include\component" -I "D:\UNISDK\ScrollShooter\VXP\ResID" -I "D:\UNISDK\ScrollShooter\VXP\src\app\widget" -I "D:\UNISDK\ScrollShooter\VXP\src\app\launcher" -I "D:\UNISDK\ScrollShooter\VXP\src\app\wallpaper" -I "D:\UNISDK\ScrollShooter\VXP\src\app\screen_lock" -I "D:\UNISDK\ScrollShooter\VXP\include\service" -I "D:\UNISDK\ScrollShooter\VXP\include\component" -I "D:\UNISDK\ScrollShooter\VXP\include\service" -I "D:\UNISDK\ScrollShooter\VXP\src\framework" -I "D:\UNISDK\ScrollShooter\VXP\src\framework\ui_core\base" -I "D:\UNISDK\ScrollShooter\VXP\src\framework\ui_core\mvc" -I "D:\UNISDK\ScrollShooter\VXP\src\framework\ui_core\pme" -I "D:\UNISDK\ScrollShooter\VXP\src\framework\mmi_core" -I "D:\UNISDK\ScrollShooter\VXP\src\ui_engine\vrt\interface" -I "D:\UNISDK\ScrollShooter\VXP\src\component" -I "D:\UNISDK\ScrollShooter\VXP\src\ui_engine\framework\xml" -I "D:\UNISDK\ScrollShooter\VXP" -errors "D:\UNISDK\ScrollShooter\VXP\VXP.log"
REM Copmile c file 
"C:\ARM\ADSv1_2\Bin\armcc" -O2 -g -apcs /ropi/rwpi -cpu ARM7EJ-S -o "D:\UNISDK\ScrollShooter\VXP\arm\gamedata.o" -c "d:\UNISDK\ScrollShooter\src\resources\gamedata.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_176X220__ -I "C:\MRE_SDK\include" -I "C:\MRE_SDK\include\service" -I "C:\MRE_SDK\include" -I "C:\MRE_SDK\include\service" -I "D:\UNISDK\ScrollShooter\VXP\include" -I "D:\UNISDK\ScrollShooter\VXP\include\service" -I "D:\UNISDK\ScrollShooter\VXP\include\component" -I "D:\UNISDK\ScrollShooter\VXP\ResID" -I "D:\UNISDK\ScrollShooter\VXP\src\app\widget" -I "D:\UNISDK\ScrollShooter\VXP\src\app\launcher" -I "D:\UNISDK\ScrollShooter\VXP\src\app\wallpaper" -I "D:\UNISDK\ScrollShooter\VXP\src\app\screen_lock" -I "D:\UNISDK\ScrollShooter\VXP\include\service" -I "D:\UNISDK\ScrollShooter\VXP\include\component" -I "D:\UNISDK\ScrollShooter\VXP\include\service" -I "D:\UNISDK\ScrollShooter\VXP\src\framework" -I "D:\UNISDK\ScrollShooter\VXP\src\framework\ui_core\base" -I "D:\UNISDK\ScrollShooter\VXP\src\framework\ui_core\mvc" -I "D:\UNISDK\ScrollShooter\VXP\src\framework\ui_core\pme" -I "D:\UNISDK\ScrollShooter\VXP\src\framework\mmi_core" -I "D:\UNISDK\ScrollShooter\VXP\src\ui_engine\vrt\interface" -I "D:\UNISDK\ScrollShooter\VXP\src\component" -I "D:\UNISDK\ScrollShooter\VXP\src\ui_engine\framework\xml" -I "D:\UNISDK\ScrollShooter\VXP" -errors "D:\UNISDK\ScrollShooter\VXP\VXP.log"
REM Link app 
"C:\ARM\ADSv1_2\Bin\armlink" -o "D:\UNISDK\ScrollShooter\VXP\VXP.axf"  "D:\UNISDK\ScrollShooter\VXP\arm\vmmain.o"  "D:\UNISDK\ScrollShooter\VXP\arm\plat_vxp.o"  "D:\UNISDK\ScrollShooter\VXP\arm\game.o"  "D:\UNISDK\ScrollShooter\VXP\arm\gamedata.o" -info totals -rwpi -ropi  "C:\MRE_SDK\lib\MRE10\armads\percommon.a" -errors "D:\UNISDK\ScrollShooter\VXP\VXP.log"
REM Add tag infromation 
"C:\MRE_SDK\tools\MRE10Tools\PackDigist.exe" "D:\UNISDK\ScrollShooter\VXP\VXP.vcproj" "ScrollShooter" "0.1.0" "monobogdan" "590" "NotSupportBg" "Not Support rotate" "ScrollShooter" "ScrollShooter" "ScrollShooter" "1234567890" "content" "" "vxp" "ADS" "VXP" "UnCompress" "Adaptable" "11534556" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\UNISDK\ScrollShooter\VXP\arm D:\UNISDK\ScrollShooter\VXP\build.log

