REM Build Bat File
REM Precheck the Resource 
"C:\MRE_SDK\tools\ResEditor\CmdShell.exe" save  "D:\UNISDK\ScrollShooter\WRE\WRE.vcproj"
REM Copmile c file 
"C:\ARM\ADSv1_2\Bin\armcc" -O2 -g -apcs /ropi/rwpi -cpu ARM7EJ-S -o "D:\UNISDK\ScrollShooter\WRE\arm\vmmain.o" -c "C:\MRE_SDK\lib\MRE20\src\vmmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_176X220__ -I "C:\MRE_SDK\include" -I "C:\MRE_SDK\include\service" -I "D:\UNISDK\ScrollShooter\WRE\include" -I "D:\UNISDK\ScrollShooter\WRE\include\service" -I "D:\UNISDK\ScrollShooter\WRE\include\component" -I "D:\UNISDK\ScrollShooter\WRE\ResID" -I "D:\UNISDK\ScrollShooter\WRE\src\app\widget" -I "D:\UNISDK\ScrollShooter\WRE\src\app\launcher" -I "D:\UNISDK\ScrollShooter\WRE\src\app\wallpaper" -I "D:\UNISDK\ScrollShooter\WRE\src\app\screen_lock" -I "D:\UNISDK\ScrollShooter\WRE\include\service" -I "D:\UNISDK\ScrollShooter\WRE\include\component" -I "D:\UNISDK\ScrollShooter\WRE\include\service" -I "D:\UNISDK\ScrollShooter\WRE\src\framework" -I "D:\UNISDK\ScrollShooter\WRE\src\framework\ui_core\base" -I "D:\UNISDK\ScrollShooter\WRE\src\framework\ui_core\mvc" -I "D:\UNISDK\ScrollShooter\WRE\src\framework\ui_core\pme" -I "D:\UNISDK\ScrollShooter\WRE\src\framework\mmi_core" -I "D:\UNISDK\ScrollShooter\WRE\src\ui_engine\vrt\interface" -I "D:\UNISDK\ScrollShooter\WRE\src\component" -I "D:\UNISDK\ScrollShooter\WRE\src\ui_engine\framework\xml" -I "D:\UNISDK\ScrollShooter\WRE" -errors "D:\UNISDK\ScrollShooter\WRE\WRE.log"
REM Copmile c file 
"C:\ARM\ADSv1_2\Bin\armcc" -O2 -g -apcs /ropi/rwpi -cpu ARM7EJ-S -o "D:\UNISDK\ScrollShooter\WRE\arm\WRE.o" -c "d:\UNISDK\ScrollShooter\WRE\WRE.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_176X220__ -I "C:\MRE_SDK\include" -I "C:\MRE_SDK\include\service" -I "D:\UNISDK\ScrollShooter\WRE\include" -I "D:\UNISDK\ScrollShooter\WRE\include\service" -I "D:\UNISDK\ScrollShooter\WRE\include\component" -I "D:\UNISDK\ScrollShooter\WRE\ResID" -I "D:\UNISDK\ScrollShooter\WRE\src\app\widget" -I "D:\UNISDK\ScrollShooter\WRE\src\app\launcher" -I "D:\UNISDK\ScrollShooter\WRE\src\app\wallpaper" -I "D:\UNISDK\ScrollShooter\WRE\src\app\screen_lock" -I "D:\UNISDK\ScrollShooter\WRE\include\service" -I "D:\UNISDK\ScrollShooter\WRE\include\component" -I "D:\UNISDK\ScrollShooter\WRE\include\service" -I "D:\UNISDK\ScrollShooter\WRE\src\framework" -I "D:\UNISDK\ScrollShooter\WRE\src\framework\ui_core\base" -I "D:\UNISDK\ScrollShooter\WRE\src\framework\ui_core\mvc" -I "D:\UNISDK\ScrollShooter\WRE\src\framework\ui_core\pme" -I "D:\UNISDK\ScrollShooter\WRE\src\framework\mmi_core" -I "D:\UNISDK\ScrollShooter\WRE\src\ui_engine\vrt\interface" -I "D:\UNISDK\ScrollShooter\WRE\src\component" -I "D:\UNISDK\ScrollShooter\WRE\src\ui_engine\framework\xml" -I "D:\UNISDK\ScrollShooter\WRE" -errors "D:\UNISDK\ScrollShooter\WRE\WRE.log"
REM Link app 
"C:\ARM\ADSv1_2\Bin\armlink" -o "D:\UNISDK\ScrollShooter\WRE\WRE.axf"  "D:\UNISDK\ScrollShooter\WRE\arm\vmmain.o"  "D:\UNISDK\ScrollShooter\WRE\arm\WRE.o" -info totals -rwpi -ropi  "C:\MRE_SDK\lib\MRE20\armads\percommon.a" "C:\MRE_SDK\lib\MRE20\armads\pertcp.a" "C:\MRE_SDK\lib\MRE20\armads\persensor.a" "C:\MRE_SDK\lib\MRE20\armads\persmsper.a" "C:\MRE_SDK\lib\MRE20\armads\perbitstream.a" "C:\MRE_SDK\lib\MRE20\armads\percontact.a" "C:\MRE_SDK\lib\MRE20\armads\permms.a" "C:\MRE_SDK\lib\MRE20\armads\persmsmng.a" -errors "D:\UNISDK\ScrollShooter\WRE\WRE.log"
REM Pack resource to app 
"C:\MRE_SDK\tools\ResEditor\CmdShell.exe" pack -silent -resolution 176x220 -o "D:\UNISDK\ScrollShooter\WRE\WRE.pkd" -e AXF "D:\UNISDK\ScrollShooter\WRE\WRE.vcproj" "D:\UNISDK\ScrollShooter\WRE\WRE.axf"
REM Add tag infromation 
"C:\MRE_SDK\tools\PackDigist.exe" "D:\UNISDK\ScrollShooter\WRE\WRE.vcproj" "ScrollShooter" "0.1.0" "monobogdan" "500" "NotSupportBg" "Not Support rotate" "ScrollShooter" "ScrollShooter" "ScrollShooter" "1234567890" "content" " TCP Sensor SMS(person) BitStream Contact MMS SMSMng" "vxp" "ADS" "PKD" "UnCompress" "NoVPI" "UnAdaptable" "11534556" "UnSysMemAble" "" "-1" "UNPUSH" "-1" "-1"  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\UNISDK\ScrollShooter\WRE\arm D:\UNISDK\ScrollShooter\WRE\build.log

